development:
  adapter: postgresql
  database: demo_app_dev
  pool: 5
  timeout: 5000

test: &test
  adapter: postgresql
  database: demo_app_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: demo_app_prod
  pool: 5
  timeout: 5000

cucumber:
  <<: *test